config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :writers
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
 belongs_to :writer
end

app/models/writer.rb
class Writer < ApplicationRecord
  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController


  def index
    @book = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_path
    else
      render 'new'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

    def book_params
      params.require(:book).permit(:writer, :name, :year, :editorial, :writer_id)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/writers_controller.rb
class WritersController < ApplicationController
  def index
    @writers = Writer.all
  end

  def show
    @writer = Writer.find(params[:id])
  end

  def new
    @writer = Writer.new
  end

  def create
    @writer = Writer.new(writer_params)
    if @writer.save
      redirect_to writers_path
    else
      render 'new'
    end
  end

  def edit
    @writer = Writer.find(params[:id])
  end

  def update
    @writer = Writer.find(params[:id])
    if @writer.update(writer_params)
      redirect_to writer_path
    else
      render :edit
    end
  end

  def destroy
    @writer = Writer.find(params[:id])
    @writer.destroy
    redirect_to writers_path
  end

  private

    def writer_params
      params.require(:writer).permit(:name, :birth, :place)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def form_books
    @book.new_record? ? "New Book" : "Edit Book"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/writers_helper.rb
module WritersHelper
  def form_writers
    @writer.new_record? ? "New Writer" : "Edit Writer"
end
end

app/views/books/_form.html.erb
<%= form_for @book do |f| %>
    <div class="grid-container">
      <div class="grid-x grid-padding-x">
        <div class="medium-6 cell">
          <lablel>
            <%= f.label :name %>
            <%= f.text_field :name %>
          </lablel>
          <lablel>
            <%= f.label :year %>
            <%= f.number_field :year %>
          </lablel>
          <lablel>
            <%= f.label :editorial %>
            <%= f.text_field :editorial %>
          </lablel>
          <lablel>
            <%= f.label :writer_id %>
            <%= f.select :writer_id, Writer.all.collect {|a| [ a.name, a.id ] } %>
          </lablel>
          <lablel>
            <%= f.submit form_books, class: "button" %>
          </lablel>

          <%= link_to "Back", books_path, class: "button" %>
        </div>
      </div>
    </div>
<% end %>

app/views/books/edit.html.erb
<%= render 'form' %>

app/views/books/index.html.erb
<h1> Books </h1>

<table class="stack">
  <thead>
    <tr>
      <th>Title</th>
      <th>view</th>
    </tr>
  </thead>
  <body>
  <% @book.each do |book| %>
    <tr>
      <td> <%= book.name %> </td>
      <td> <%= link_to "info", book_path(book) %> </td>
    </tr>
  <% end %>
  </body>
</table>

<%= link_to "Create book", new_book_path, class: "button" %>

<%= link_to "Home", root_path, class: "button" %>

app/views/books/new.html.erb
<%= render 'form' %>

app/views/books/show.html.erb
<h1> <%= @book.name %> </h1>

<div>
  <span>Title</span> <%= @book.name %>
</div>

<div>
  <span>Year</span> <%= @book.year %>
</div>

<div>
  <span>Editorial</span> <%= @book.editorial %>
</div>

<div>Writer:
   <%= @book.writer.name if @book.writer %>
   <%= link_to "Info", writer_path(@book.writer) if @book.writer %>
</div>

<%= link_to "Edit", edit_book_path(@book), class: "button" %>

<%= link_to "Delete", @book, class: "button", method: :delete, data: { confirm: "¿Are you shure?" } %>

<%= link_to "Back", books_path, class: "button" %>

app/views/home/index.html.erb
<h1>Library</h1>

<div class="expanded button-group">
  <%= link_to "Writer", writers_path, class: "button" %>
  <%= link_to "Books", books_path, class: "button" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/writers/_form.html.erb
<%= form_for @writer do |f| %>
    <div class="grid-container">
      <div class="grid-x grid-padding-x">
        <div class="medium-6 cell">
          <lablel>
            <%= f.label :name %>
            <%= f.text_field :name %>
          </lablel>
          <lablel>
            <%= f.label :birth %>
            <%= f.number_field :birth %>
          </lablel>
          <lablel>
            <%= f.label :place %>
            <%= f.text_field :place %>
          </lablel>

          <%= f.submit form_writers, class: "button" %>

          <%= link_to "Back", writers_path, class: "button" %>

        </div>
      </div>
    </div>
<% end %>

app/views/writers/edit.html.erb
<%= render 'form' %>

app/views/writers/index.html.erb
<h1> Writers </h1>

<table class="stack">
  <thead>
    <tr>
      <th>Name</th>
      <th>view</th>
    </tr>
  </thead>
  <body>
  <% @writers.each do |writer| %>
    <tr>
      <td> <%= writer.name %> </td>
      <td> <%= link_to "info", writer_path(writer) %> </td>
    </tr>
  <% end %>
  </body>
</table>


<%= link_to "Create writer", new_writer_path, class: "button" %>
<%= link_to "Home", root_path, class: "button" %>

app/views/writers/new.html.erb
<%= render 'form' %>

app/views/writers/show.html.erb
<h1> <%= @writer.name %>

<div>
  <span>Bird</span> <%= @writer.birth %>
</div>

<div>
  <span>Place</span> <%= @writer.place %>
</div>

<div>
  <% if @writer.books.length == 0 %>
        <h3>Don't Have books</h3>
      <%else%>
        <h3>books</h3>
          <div>
            <ul>
              <% @writer.books.each_with_index do |v,i| %>
                <li><%= link_to v.name, book_path(v)%></li>
              <%end%>
            </ul>
          </div>
      <%end%>
</div>

<%= link_to "Edit", edit_writer_path(@writer), class: "button" %>

<%= link_to "Delete", @writer, class: "button", method: :delete, data: { confirm: "¿Are you shure?" } %>

<%= link_to "Back", writers_path, class: "button" %>